name: Folio
favicon: null
layout_spectrum: 0.76384
typography_spectrum: 0.53654
title: title is for noobs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#2c3b3e'
    - '#ded4cb'
    - '#9f9967'
    - '#616061'
  brandStrength: 0.45172330900095403
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
