name: Folio
favicon: null
layout_spectrum: 0.7376
typography_spectrum: 0.53654
title: 'title is for noobs asdasd '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f9'
    - '#c0baba'
    - '#002c41'
    - '#9a9691'
    - '#3a5c60'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
